### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by lisahligono** [ZGIS/semantique#24] opened 2023-04-18 12:55 UTC
### Discussed in https://github.com/ZGIS/semantique/discussions/23

<div type='discussions-op-text'>

<sup>Originally posted by **lisahligono** April 18, 2023</sup>
I would like to ask if it's possible to get the full documentation of the opendatacube and geotiffarchive configuration </div>

**Comment by luukvdmeer** [comment] 2023-07-12 08:05
Close as duplicate of #10

**Closed by luukvdmeer** 2023-07-12 08:05 UTC
